Add regression test for issue 177
Currently fails with:

    error[E0309]: the parameter type `impl FnMut(&'life1 str) + Send` may not live long enough
        --> tests/test.rs:1383:68
         |
    1383 |         async fn foo(&self, mut callback: impl FnMut(&str) + Send) {}
         |                                                                    ^^ ...so that the type `impl futures::Future<Output = ()>` will meet its required lifetime bounds
         |
    help: consider adding an explicit lifetime bound...
         |
    1383 |         async fn foo(&self, mut callback: impl FnMut(&str) + Send + 'async_trait) {}
         |                                                                   ++++++++++++++