Add regression test for issue 281
Without #![feature(impl_trait_in_bindings)]:

    error[E0562]: `impl Trait` is not allowed in paths
        --> tests/test.rs:1680:42
         |
    1680 |         async fn method(&self) -> Result<impl AsRef<str> + Send + Sync, Self::Error> {
         |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         |
         = note: `impl Trait` is only allowed in arguments and return types of functions and methods

    error[E0562]: `impl Trait` is not allowed in the type of variable bindings
        --> tests/test.rs:1680:42
         |
    1680 |         async fn method(&self) -> Result<impl AsRef<str> + Send + Sync, Self::Error> {
         |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         |
         = note: `impl Trait` is only allowed in arguments and return types of functions and methods
         = note: see issue #63065 <https://github.com/rust-lang/rust/issues/63065> for more information
         = help: add `#![feature(impl_trait_in_bindings)]` to the crate attributes to enable
         = note: this compiler was built on 2025-01-02; consider upgrading it if it is out of date

With #![feature(impl_trait_in_bindings)]:

    error[E0562]: `impl Trait` is not allowed in paths
        --> tests/test.rs:1680:42
         |
    1680 |         async fn method(&self) -> Result<impl AsRef<str> + Send + Sync, Self::Error> {
         |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         |
         = note: `impl Trait` is only allowed in arguments and return types of functions and methods