Add regression test for issue 234
Currently fails to compile:

    error: changes to closure capture in Rust 2021 will affect drop order
        --> tests/test.rs:1549:59
         |
    1549 |         async fn f(Tuple(_, _int): Tuple<Droppable, i32>) {}
         |                    --------------                         ^-
         |                    |                                       |
         |                    |                                       in Rust 2018, `__arg0` is dropped here, but in Rust 2021, only `__arg0.1` will be dropped here as part of the closure
         |                    in Rust 2018, this closure captures all of `__arg0`, but in Rust 2021, it will only capture `__arg0.1`
         |
         = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/disjoint-capture-in-closures.html>
    note: the lint level is defined here
        --> tests/test.rs:5:9
         |
    5    | #![deny(rust_2021_compatibility)]
         |         ^^^^^^^^^^^^^^^^^^^^^^^
         = note: `#[deny(rust_2021_incompatible_closure_captures)]` implied by `#[deny(rust_2021_compatibility)]`
    help: add a dummy let to cause `__arg0` to be fully captured
         |
    1549 |         async fn f(Tuple(_, _int): Tuple<Droppable, i32>) { let _ = &__arg0;}
         |                                                             ++++++++++++++++

    error: changes to closure capture in Rust 2021 will affect drop order
        --> tests/test.rs:1556:66
         |
    1556 |         async fn f(Tuple { 1: _int, .. }: Tuple<Droppable, i32>) {}
         |                    ---------------------                         ^-
         |                    |                                              |
         |                    |                                              in Rust 2018, `__arg0` is dropped here, but in Rust 2021, only `__arg0.1` will be dropped here as part of the closure
         |                    in Rust 2018, this closure captures all of `__arg0`, but in Rust 2021, it will only capture `__arg0.1`
         |
         = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/disjoint-capture-in-closures.html>
    help: add a dummy let to cause `__arg0` to be fully captured
         |
    1556 |         async fn f(Tuple { 1: _int, .. }: Tuple<Droppable, i32>) { let _ = &__arg0;}
         |                                                                    ++++++++++++++++