Add regression test for issue 283
    error[E0276]: impl has stricter requirements than trait
        --> tests/test.rs:1699:5
         |
    1692 |         async fn a();
         |         ------------- definition of `a` from trait
    ...
    1699 |     #[async_trait]
         |     ^^^^^^^^^^^^^^ impl has extra requirement `T: 'async_trait`
         |
         = note: this error originates in the attribute macro `async_trait` (in Nightly builds, run with -Z macro-backtrace for more info)