Avoid cargo 1.43–1.45 in GitHub Actions
These versions are incompatible with some recent GitHub change.

    error: failed to get `proc-macro2` as a dependency of package `async-trait v0.1.56 (/home/runner/work/async-trait/async-trait)`

    Caused by:
      failed to load source for dependency `proc-macro2`

    Caused by:
      Unable to update registry `https://github.com/rust-lang/crates.io-index`

    Caused by:
      failed to fetch `https://github.com/rust-lang/crates.io-index`

    Caused by:
      error reading from the zlib stream; class=Zlib (5)