Raise minimum tested version to 1.40
1.39 is still supported but tracing-attributes in our test deps assumes 1.40.

    error[E0658]: use of unstable library feature 'option_flattening'
       --> tracing-attributes-0.1.10/src/lib.rs:933:10
        |
    933 |         .flatten();
        |          ^^^^^^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/60258