Add regression test for issue 236
Currently fails:

    error: an async construct yields a type which is itself awaitable
        --> tests/test.rs:1582:35
         |
    1582 |           async fn f() -> Ready<()> {
         |  ___________________________________^
    1583 | |             future::ready(())
    1584 | |         }
         | |         ^
         | |         |
         | |_________outer async construct
         |           awaitable value not awaited
         |
         = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#async_yields_async
    note: the lint level is defined here
        --> tests/test.rs:1562:13
         |
    1562 |     #![deny(clippy::async_yields_async)]
         |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    help: consider awaiting this value
         |
    1582 ~         async fn f() -> Ready<()> {
    1583 +             future::ready(())
    1584 +         }.await
         |