Add regression test for issue 238
Currently fails:

    error: lifetime parameter `'impl0` only used once
        --> tests/test.rs:1603:20
         |
    1603 |     impl Trait for &Struct {
         |                    ^
         |                    |
         |                    this lifetime...
         |                    ...is used only here
         |
    note: the lint level is defined here
        --> tests/test.rs:1591:13
         |
    1591 |     #![deny(single_use_lifetimes)]
         |             ^^^^^^^^^^^^^^^^^^^^
    help: elide the single-use lifetime
         |
    1602 ~
    1603 ~     impl Trait for Struct {
         |