Raise minimum tested version to rustc 1.45
Required by changes in the futures crate's macros:

    error[E0658]: procedural macros cannot be expanded to statements
        --> tests/test.rs:1359:13
         |
    1359 | /             futures::select! {
    1360 | |                 _ = async {
    1361 | |                     println!("{}", self.0);
    1362 | |                 }.fuse() => {}
    1363 | |             }
         | |_____________^